name: organoid_roi_incucyte_imaging
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas>=2.2
  - tifffile>=2024.2.12
  - pytest>=8
  - imagecodecs>=2024.1
  - pillow>=10.3
  - h5py>=3.10
  - matplotlib>=3.8
  - pip
  - pip:
      - napari>=0.4.19
      - PySide6>=6.6
      - scikit-image>=0.22
      - pyinstaller>=6.5
